/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-10-20 00:55:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.example.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/jodon/OneDrive/Desktop/egovframework/eGovFrameDev-3.8.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test4Proceeding/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1582010903301L));
    _jspx_dependants.put("jar:file:/C:/Users/jodon/OneDrive/Desktop/egovframework/eGovFrameDev-3.8.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test4Proceeding/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1599697216655L));
    _jspx_dependants.put("jar:file:/C:/Users/jodon/OneDrive/Desktop/egovframework/eGovFrameDev-3.8.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test4Proceeding/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css\"\r\n");
      out.write("\tintegrity=\"sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"/css/test/test.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1>게시판List</h1>\r\n");
      out.write("\t\t<div class=\"testlist\">\r\n");
      out.write("\t\t\t<form id=\"boardForm\" name=\"boardForm\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"20%\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"50%\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"15%\" />\r\n");
      out.write("\t\t\t\t\t\t<col width=\"15%\" />\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>등록일자</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody id=\"dataSection\"></tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<button id=\"btn_write\" type=\"button\">글작성</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- pagination{s} -->\r\n");
      out.write("\t\t<div class=\"pagination1\">\r\n");
      out.write("\t\t\t<ul id=\"paginationBox\" class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- pagination{e} -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- search{s} -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"form-group row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"w100\" style=\"padding-right: 10px\">\r\n");
      out.write("\t\t\t\t<select class=\"form-control form-control-sm\" id=\"keywordType\">\r\n");
      out.write("\t\t\t\t\t<option value=\"testTitle\">제목</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"testContent\">본문</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"testName\">작성자</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"w300\" style=\"padding-right: 10px\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control form-control-sm\"\r\n");
      out.write("\t\t\t\t\tname=\"keyword\" id=\"keyword\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-sm btn-primary\" name=\"btnSearch\"\r\n");
      out.write("\t\t\t\t\tid=\"btnSearch\">검색</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- search{e} -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 페이지 목록 갯수   -->\r\n");
      out.write("\t\t<div class=\"form-group row justify-content-center\">\r\n");
      out.write("\t\t\t<p>게시판 목록 갯수</p>\r\n");
      out.write("\t\t\t<div class=\"w100\" style=\"padding-right: 10px\">\r\n");
      out.write("\t\t\t\t<select id=\"listSize\" class=\"form-control form-control-sm\">\r\n");
      out.write("\t\t\t\t\t<option value=\"10\">10 개</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"15\">15 개</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"20\">20 개</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<input type=\"hidden\" id=\"searchInput\" value=\"\" />\r\n");
      out.write("\t<input type=\"hidden\" id=\"searchType\" value=\"testTitle\" />\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tgetPage();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$(\"#listSize\").change(function() {\r\n");
      out.write("\t\tgetPage();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//\t글조회\r\n");
      out.write("\t//\t어떤 게시물을 클릭했는지 게시물의 번호(testId)를 넘겨 줘야 함 따라서 게시물 클릭 이벤트에서 게시물의 번호를 인자 값으로 받습니다.\r\n");
      out.write("\t//  get 방식으로 데이터를 전송합니다. 따라서 ? 연산자를 사용해 testId를 주소 뒤에 붙여 줍니다\r\n");
      out.write("\tfunction showDetail(testId) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar form = document.getElementById(\"boardForm\");\r\n");
      out.write("\t\tvar url = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\turl = url + \"?testId=\" + testId;\r\n");
      out.write("\r\n");
      out.write("\t\tform.action = url;\r\n");
      out.write("\t\tform.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//글 작성 버튼 클릭 시 testRegister로 이동\r\n");
      out.write("\t$(\"#btn_write\").click(function javascript_onclikc() {\r\n");
      out.write("\t\t$(location).attr('href', 'testRegister.do');\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#btnSearch\").click(function() {\r\n");
      out.write("\t\tconst search = $(\"#keyword\").val();\r\n");
      out.write("\t\tconst searchType = $(\"#keywordType\").val();\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#searchInput\").val(search);\r\n");
      out.write("\t\t$(\"#searchType\").val(searchType);\r\n");
      out.write("\t\tgetPage();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction getPage(page) {\r\n");
      out.write("\t\tvar listSize = $(\"#listSize\").val();\r\n");
      out.write("\t\tvar searchType = $(\"#searchType\").val();\r\n");
      out.write("\t\tvar search = $(\"#searchInput\").val();\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"getTestList.do\", //서비스 주소 \r\n");
      out.write("\t\t\t\t\tdata : { //서비스 처리에 필요한 인자값\r\n");
      out.write("\t\t\t\t\t\tpage : page,\r\n");
      out.write("\t\t\t\t\t\tsearchType : searchType,\r\n");
      out.write("\t\t\t\t\t\tkeyword : search,\r\n");
      out.write("\t\t\t\t\t\tlistSize : listSize\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\t\t\tconst list = res['list'];\r\n");
      out.write("\t\t\t\t\t\tconst pagination = res['pagination'];\r\n");
      out.write("\t\t\t\t\t\tvar data = \"\";\r\n");
      out.write("\t\t\t\t\t\tvar block = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tconsole.log(pagination);\r\n");
      out.write("\t\t\t\t\t\t// 테이블의 row를 삽입하는 부분\r\n");
      out.write("\t\t\t\t\t\tfor (var i = 0; i < list.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tdata += \"<tr style='cursor:pointer' onclick='showDetail(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ list[i]['testId'] + \")'>\";\r\n");
      out.write("\t\t\t\t\t\t\tdata += \"<td>\" + list[i]['testId'] + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tdata += \"<td>\" + list[i]['testTitle'] + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tdata += \"<td>\" + list[i]['testName'] + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tdata += \"<td>\" + list[i]['testDate'] + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\tdata += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 이전버튼 활성화 여부를 결정하는 부분\r\n");
      out.write("\t\t\t\t\t\tif (pagination['prev']) {\r\n");
      out.write("\t\t\t\t\t\t\tblock += \"<li class='page-item'><a class='page-link' href='javascript:getPage(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ (pagination['startPage'] - 1)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \")'> < </a></li>\";\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tblock += \"<li class='page-item disabled'><a class='page-link'> < </a></li>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// 번호를 표시하는 부분\r\n");
      out.write("\t\t\t\t\t\tfor (var i = pagination['startPage']; i < pagination['endPage']; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tif (page !== i) {\r\n");
      out.write("\t\t\t\t\t\t\t\tblock += \"<li class='page-item'><a class='page-link' href='javascript:getPage(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ i + \")'>\" + (i + 1) + \"</a></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tblock += \"<li class='page-item disabled'><a class='page-link'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ (i + 1) + \"</a></li>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif (pagination['next']) {\r\n");
      out.write("\t\t\t\t\t\t\tblock += \"<li class='page-item'><a class='page-link' href='javascript:getPage(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ (pagination['endPage'])\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \")'>  > </a></li>\";\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\tblock += \"<li class='page-item disabled'><a class='page-link'> > </a></li>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$(\"#dataSection\").html(data);\r\n");
      out.write("\t\t\t\t\t\t$(\"#paginationBox\").html(block);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/test/testList.jsp(118,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/testDetail.do");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
