/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2020-10-20 00:37:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.example.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/jodon/OneDrive/Desktop/egovframework/eGovFrameDev-3.8.0-64bit/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/boardTest_AJAX/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1599697216655L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<h1>글쓰기</h1>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<!-- enctype=\"multipart/form-data\" 이 부분을 사용해 줘야지만 파일을 전송할 수 있다. -->\r\n");
      out.write("\t\t\t\t<form id=\"form_test\" action=\"insertTest.do\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tencType=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>제목:</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" placeholder=\"제목을 입력하세요. \"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"testTitle\" id=\"testTitle\" class=\"form-control\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>내용:</th>\r\n");
      out.write("\t\t\t\t\t\t<td><textarea placeholder=\"내용을 입력하세요 . \" id=\"testContent\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"testContent\" class=\"form-control\" style=\"height: 200px;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>첨부파일:</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"file\" id=\"uploadFile\" name=\"uploadFile\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"btn_register\" type=\"button\" class=\"btn btn_register\">등록</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button id=\"btn_previous\" type=\"button\" class=\"btn btn_previous\">이전</button>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//글쓰기\r\n");
      out.write("\t$(document).on('click', '#btn_register', function(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t//데이터를 담아내는 부분 상수 const로\r\n");
      out.write("\t\t//jquery val() : Form Element 의 값을 받아오는데 쓰인다. (주로 input 이나 textarea 정도?)- 주의해야할 점은 Form Element 이외의 값은 받아오질 못한다는 점.\r\n");
      out.write("\t\t//문자열 좌우에서 공백을 제거하는 함수가 trim() 함수 입니다.\r\n");
      out.write("\t\tconst testTitle = $(\"#testTitle\").val().trim();\r\n");
      out.write("\t\tconst testContent = $(\"#testContent\").val().trim();\r\n");
      out.write("\t\tconst uploadFile = $(\"#uploadFile\")[0].files[0];\r\n");
      out.write("\r\n");
      out.write("\t\t//'==' 연산자를 이용하여 서로 다른 유형의 두 변수의 [값] 비교\r\n");
      out.write("\t\t//'==='는 엄격한 비교를 하는 것으로 알려져 있다 ([값 & 자료형] -> true). 변수를 비교하거나 어떤 비교를 위해 항상 '===' 연산자를 사용 할 것을 권장한다.\r\n");
      out.write("\t\tif (testTitle === '') {\r\n");
      out.write("\t\t\talert('제목을 입력해주세요.');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (testContent === '') {\r\n");
      out.write("\t\t\talert('내용을 입력해주세요.');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//ajax 통신을 사용해 서버에 데이터를 전송하기 위해 \r\n");
      out.write("\t\t//폼데이터 객체를 생성함\r\n");
      out.write("\t\t//jquery의 append를 통해서 프로퍼티에 바인딩이 가능하도록 세팅한다..append()선택된 요소의 마지막에 새로운 요소나 콘텐츠를 추가한다.\r\n");
      out.write("\t\tvar formData = new FormData();\r\n");
      out.write("\t\tformData.append(\"testTitle\", testTitle);\r\n");
      out.write("\t\tformData.append(\"testContent\", testContent);\r\n");
      out.write("\r\n");
      out.write("\t\t//만약 uploadFile이 undifined거나 null일 경우 폼데이터에 보내지 않도록 한다.\r\n");
      out.write("\t\t//이부분 체크하지 않을 경우 undifined가 데이터로 보내지기 때문에 서버에서 에러가 발생한다.\r\n");
      out.write("\t\tif (uploadFile)\r\n");
      out.write("\t\t\tformData.append(\"uploadFile\", uploadFile);\r\n");
      out.write("\r\n");
      out.write("\t\t//ajax로 파일전송 폼데이터를 보내기위해\r\n");
      out.write("\t\t//enctype, processData, contentType 이 세가지를 반드시 세팅해야한다.\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\tenctype : 'multipart/form-data',\r\n");
      out.write("\t\t\tprocessData : false,\r\n");
      out.write("\t\t\tcontentType : false,\r\n");
      out.write("\t\t\tcache : false,\r\n");
      out.write("\t\t\turl : \"./insertTest.do\",\r\n");
      out.write("\t\t\tdata : formData,\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tsuccess : function(res) {\r\n");
      out.write("\t\t\t\talert('게시글 등록 완료');\r\n");
      out.write("\t\t\t\tlocation.href = \"./testList.do\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//이전 클릭 시 testList로 이동\r\n");
      out.write("\t$(\"#btn_previous\").click(function javascript_onclikc() {\r\n");
      out.write("\t\t$(location).attr('href', 'testList.do');\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
